### ISSUE TITLE
Wiring for NF-A4x10

### ISSUE THREAD

**Issue by wormscoffer** [ziggymax/pi-fan#12]
Firstly, thanks for the work done on this.

I have wired as per your instructions but it didn't work. I then dissasembled and checked the wires and on my fan (same model as yours) it seems the yellow lead is +5V.

On checking the website of the manufacturer, this seems to be confirmed.

![image](https://user-images.githubusercontent.com/12325226/70137137-96894600-168d-11ea-8e3b-b5231768e0bf.png)

https://noctua.at/media/wysiwyg/faqs/noctua_pin_configuration_5v_fans.png

**Comment by ziggymax** [comment]
Indeedy, you are right! I'll update the documentation (the figure) asap.

**Comment by ziggymax** [comment]
The fan wiring figure has been updated to match Noctua's diagram. Weird really, that I goofed up on the wiring diagram. Looking at my own Pi+fan, it of course uses the green/yellow wires as shown by Noctua. But I obviously managed to swap them on the diagram ....
